### ISSUE TITLE
[refactor] Name 값 객체로 전환

### ISSUE THREAD

**Issue by KWY0218** [ASAP-as-soon-as-possible/ASAP_Server#309]
## 📌  Feature Issue
- Action
웹 계층에서 Validation 어노테이션으로 진행한 유효성 검사를 도메인 내부에서 진행하기

- 이유
1. 예를 들어서 '사용자 이름은 8자를 초과하면 안된다.' 규칙을 각 RequestDto 내부에서 Validation 어노테이션을 통해 진행중입니다. 하지만 해당 규칙이 변경된다면 '회의 시간 입력 API', '로그인 API' 등으로 해당 수정 사항이 전파됩니다.
2. dto는 Data Transfer Object로 계층 간 값을 전달이 목적인 객체입니다. 여기서 유효성 검사를 하는 것에 어색함을 느꼈습니다..!

- 결론
값 객체를 만들어서 유효성 검사를 도메인 내부에서 진행하도록 만들 것입니다.
또한, request dto에 붙어있는 Validation 어노테이션을 점진적으로 없애볼 생각입니다..!

**Comment by sohyundoh** [comment]
좋은 생각인 것 같습니다! 
저도 해당 형식으로 타 프로젝트를 검토하고 있었는데, 저는 유효하지 않은 요청에 대해서 Service 로직을 타게 해야할까 라는 고민을 했습니다! 혹시 검증을 웹 계층에서 하는 것은 어떻게 생각하시나요?
+ ) 만약 어노테이션을 없애신다면 혹시 Validator나 다른 Validation용 클래스를 만드는 방법인가요?

**Comment by KWY0218** [comment]
@sohyundoh 
Validator class를 만들어서 웹 계층에서 검증하는 방식도 고려해봤으나
'비밀번호는 최대 4자이다.', '이름은 최대 8자이다' 등과 같은 요구사항이 **도메인 로직에 가깝다고 판단**해 
웹 계층이 아닌 도메인 계층에서 적용하려 했습니다.

또, 별도의 validate 클래스를 만드는 것이 아닌 **값 객체**를 만들어서 적용해보려 합니다..!
[예시 블로그](https://www.cckn.dev/backend/20230903%20--%20ddd-2-value-object/) 참고하면 좋을 것 같습니다.

또한 [해당 커밋](https://github.com/ASAP-as-soon-as-possible/ASAP_Server/commit/94861fb460bed0afb9e2496135c5465c4b250c72) 과 같이 작업할 예정입니다
